debug: incremental rebuild - re-add npm install

diff --git a/.github/workflows/android_build.yml b/.github/workflows/android_build.yml
--- a/.github/workflows/android_build.yml
+++ b/.github/workflows/android_build.yml
@@ -33,3 +33,9 @@ jobs:
         echo "Current Workdir: $(pwd)"
         ls -la
 
+    - name: Install dependencies
+      run: |
+        npm install --legacy-peer-deps
+        echo "Listing node_modules..."
+        ls -d node_modules/ || echo "node_modules missing!"
+
